"""Unit tests for the Gaussian-cube reader (orcamgr.cube).

The header parse exists for one reason: ORCA writes the *orbital* variant of the
cube format, where the atom count is negative and an extra line of MO indices
sits between the atom block and the values. A reader that misses that is off by
one line, so the negative-count case is pinned here against a fixture shaped
exactly like a real ORCA cube (verified against orca_plot 6.1.1 output).
"""

import pytest

from orcamgr.cube import (
    DEFAULT_ISOVALUES, SIGNED_KINDS, load_cube, read_cube_header,
)


def _cube(natoms: int = -2, nx: int = 2, ny: int = 2, nz: int = 2,
          mo_line: bool = True, title: str = "Molecular orbital 96 of operator 0") -> str:
    """A minimal cube. natoms < 0 adds the MO-index line, as ORCA writes it."""
    lines = ["Cube data generated by ORCA", title,
             f"{natoms:5d}  -16.362654  -16.515994   -8.984968",
             f"{nx:5d}    0.584071    0.000000    0.000000",
             f"{ny:5d}    0.000000    0.489471    0.000000",
             f"{nz:5d}    0.000000    0.000000    0.460551"]
    for _ in range(abs(natoms)):
        lines.append("    8   8.000000   0.000000   0.000000   0.117300")
    if natoms < 0 and mo_line:
        lines.append("    1   96")
    values = ["   0.00000E+00"] * (nx * ny * nz)
    lines += [" ".join(values[i:i + 6]) for i in range(0, len(values), 6)]
    return "\n".join(lines) + "\n"


def _write(tmp_path, text, name="t.cube"):
    p = tmp_path / name
    p.write_text(text, encoding="utf-8")
    return p


# --- header ------------------------------------------------------------------

def test_negative_atom_count_is_the_orca_orbital_variant(tmp_path):
    """-52 atoms means 52 atoms plus an MO-index line, not a broken file."""
    h = read_cube_header(_write(tmp_path, _cube(natoms=-52, nx=60, ny=60, nz=60)))
    assert h["ok"] is True
    assert h["natoms"] == 52
    assert (h["nx"], h["ny"], h["nz"]) == (60, 60, 60)
    assert h["npoints"] == 60 ** 3


def test_positive_atom_count_still_parses(tmp_path):
    h = read_cube_header(_write(tmp_path, _cube(natoms=3, mo_line=False)))
    assert h["ok"] is True and h["natoms"] == 3


def test_title_is_orcas_own_description(tmp_path):
    """The caption must say what ORCA plotted, not what we asked for."""
    h = read_cube_header(_write(tmp_path, _cube(title="Total electron density")))
    assert h["title"] == "Total electron density"


def test_origin_is_read(tmp_path):
    h = read_cube_header(_write(tmp_path, _cube()))
    assert h["origin"] == pytest.approx([-16.362654, -16.515994, -8.984968])


@pytest.mark.parametrize("text", [
    "",                                   # empty
    "one\ntwo\n",                         # truncated header
    "not\na\ncube\nat\nall\nreally\n",    # six lines, no numbers
])
def test_malformed_files_are_reported_never_raised(tmp_path, text):
    h = read_cube_header(_write(tmp_path, text))
    assert h["ok"] is False and h["error"]


def test_degenerate_grid_is_rejected(tmp_path):
    h = read_cube_header(_write(tmp_path, _cube(nx=0)))
    assert h["ok"] is False


def test_missing_file_gets_a_plain_sentence(tmp_path):
    h = read_cube_header(tmp_path / "gone.cube")
    assert h["ok"] is False
    assert "no longer on disk" in h["error"]


# --- load_cube ---------------------------------------------------------------

def test_load_returns_the_file_verbatim(tmp_path):
    """3Dmol parses the cube text itself, so it must arrive unmodified."""
    text = _cube()
    d = load_cube(_write(tmp_path, text), "mo")
    assert d["ok"] is True
    assert d["text"] == text
    assert d["dims"] == [2, 2, 2] and d["npoints"] == 8


@pytest.mark.parametrize("kind,signed", [("mo", True), ("spindens", True), ("eldens", False)])
def test_only_signed_kinds_get_a_negative_lobe(tmp_path, kind, signed):
    """An electron density is positive everywhere; a second surface would be noise."""
    d = load_cube(_write(tmp_path, _cube()), kind)
    assert d["signed"] is signed
    assert d["isovalue"] == DEFAULT_ISOVALUES[kind]
    assert (kind in SIGNED_KINDS) is signed


def test_oversize_cube_is_refused_before_it_reaches_the_ui(tmp_path):
    """P48: the payload cap is checked on the file, not after reading it in."""
    d = load_cube(_write(tmp_path, _cube(nx=8, ny=8, nz=8)), "mo", max_bytes=50)
    assert d["ok"] is False
    assert "coarser grid" in d["error"]
    assert "text" not in d


def test_no_cap_means_no_limit(tmp_path):
    assert load_cube(_write(tmp_path, _cube()), "mo", max_bytes=0)["ok"] is True


def test_load_rejects_a_non_cube_without_reading_it_all(tmp_path):
    d = load_cube(_write(tmp_path, "garbage\n" * 10), "mo")
    assert d["ok"] is False and "text" not in d


def test_an_nbo_draws_like_an_mo():
    """Signed (two lobes) and opened at the orbital convention, which the
    viewer then lowers to the enclosed-fraction fit as for any orbital."""
    assert "nbo" in SIGNED_KINDS
    assert DEFAULT_ISOVALUES["nbo"] == DEFAULT_ISOVALUES["mo"]
