"""Unit tests for natural-bond-orbital cubes (orcamgr.nbo.cubes) and the
orbital set behind them (NboOrbitalSet in orcamgr.nbo.analysis).

The point of the reuse rule is pinned here: an NBO index is a position the
Lewis search assigned, not a physical label, so a cube is served again only
when it is newer than the wavefunction AND names the analysis format that
wrote it. Everything runs on the water fixture, ORCA-free.
"""

import os
import time
from pathlib import Path

import numpy as np
import pytest

from orcamgr.core.plot import CubeRequest, cube_filename
from orcamgr.cube import read_cube_header
from orcamgr.nbo.analysis import CACHE_FORMAT, NboOrbitalSet, analyze_set
from orcamgr.nbo.cubes import GENERATOR_LINE, cube_title, generate_nbo_cube, is_current
from orcamgr.nbo.wavefunction import WavefunctionError, load_molden

FIXTURES = Path(__file__).parent / "nbo" / "fixtures"


@pytest.fixture(scope="module")
def water() -> NboOrbitalSet:
    return NboOrbitalSet.from_wavefunction(load_molden(FIXTURES / "h2o.molden.input"),
                                          source_mtime=1000.0)


@pytest.fixture(scope="module")
def cation() -> NboOrbitalSet:
    return NboOrbitalSet.from_wavefunction(load_molden(FIXTURES / "h2o_cation.molden.input"))


# --- the orbital set ----------------------------------------------------------

def test_the_set_addresses_orbitals_by_position(water):
    basis = water.basis(0)
    assert water.orbital(0, 3) is basis.orbitals[3]
    assert basis.orbitals[3].index == 3


def test_ao_coefficients_give_a_normalized_orthogonal_orbital(water):
    """Back in the AO basis the orbital has unit norm in the S metric and is
    S-orthogonal to its neighbours -- NAO -> NBO -> AO composed the right way."""
    S = water.wavefunction.overlap()
    a = water.ao_coefficients(0, 1)
    b = water.ao_coefficients(0, 3)
    assert float(a @ S @ a) == pytest.approx(1.0, abs=1e-8)
    assert float(b @ S @ b) == pytest.approx(1.0, abs=1e-8)
    assert float(a @ S @ b) == pytest.approx(0.0, abs=1e-8)


def test_a_closed_shell_has_no_beta_set(water):
    with pytest.raises(WavefunctionError, match="closed-shell"):
        water.basis(1)


def test_an_open_shell_has_two_sets(cation):
    assert cation.basis(0).spin == "alpha" and cation.basis(1).spin == "beta"
    assert cation.ao_coefficients(1, 0).shape == (cation.wavefunction.n_basis,)


def test_an_index_out_of_range_says_how_many_there_are(water):
    with pytest.raises(WavefunctionError, match="out of range"):
        water.orbital(0, 10_000)


def test_the_table_rows_carry_the_same_index_the_set_uses(water):
    analysis = analyze_set(water, "h2o")
    rows = analysis.lewis[0].orbitals
    for row in rows:
        assert water.orbital(0, row.index).label(water.wavefunction.elements) == row.label
    assert analysis.format == CACHE_FORMAT


# --- generation ---------------------------------------------------------------

def test_generate_writes_the_cube_under_the_shared_name(tmp_path, water):
    req = CubeRequest(kind="nbo", index=1, operator=0, grid=40)
    res = generate_nbo_cube(water, "h2o", req, dest_dir=tmp_path)
    assert res["ok"] and not res["cached"]
    assert Path(res["path"]).name == cube_filename("h2o", req) == "h2o.nbo1a.g40.cube"
    assert res["label"] == "LP (1) O1"
    lines = Path(res["path"]).read_text(encoding="utf-8").splitlines()
    assert lines[0] == GENERATOR_LINE
    assert lines[1].startswith("Natural bond orbital 1: LP (1) O1, occupancy ")
    header = read_cube_header(res["path"])
    assert header["ok"] and (header["nx"], header["ny"], header["nz"]) == (40, 40, 40)


def test_a_current_cube_is_reused(tmp_path, water):
    req = CubeRequest(kind="nbo", index=2, grid=40)
    first = generate_nbo_cube(water, "h2o", req, dest_dir=tmp_path)
    again = generate_nbo_cube(water, "h2o", req, dest_dir=tmp_path)
    assert first["ok"] and again["ok"] and again["cached"]
    assert again["path"] == first["path"] and again["label"] == "LP (2) O1"


def test_a_cube_from_another_format_is_regenerated(tmp_path, water):
    req = CubeRequest(kind="nbo", index=2, grid=40)
    path = tmp_path / cube_filename("h2o", req)
    path.write_text("Cube data generated by ORCAdesk (NBO format 1)\nold\n", encoding="utf-8")
    assert not is_current(path, water.source_mtime)
    res = generate_nbo_cube(water, "h2o", req, dest_dir=tmp_path)
    assert res["ok"] and not res["cached"]
    assert path.read_text(encoding="utf-8").splitlines()[0] == GENERATOR_LINE


def test_a_cube_older_than_the_wavefunction_is_regenerated(tmp_path, water):
    req = CubeRequest(kind="nbo", index=2, grid=40)
    path = tmp_path / cube_filename("h2o", req)
    generate_nbo_cube(water, "h2o", req, dest_dir=tmp_path)
    os.utime(path, (water.source_mtime - 10, water.source_mtime - 10))
    assert not is_current(path, water.source_mtime)
    res = generate_nbo_cube(water, "h2o", req, dest_dir=tmp_path)
    assert res["ok"] and not res["cached"]


def test_reuse_false_regenerates(tmp_path, water):
    req = CubeRequest(kind="nbo", index=2, grid=40)
    generate_nbo_cube(water, "h2o", req, dest_dir=tmp_path)
    res = generate_nbo_cube(water, "h2o", req, dest_dir=tmp_path, reuse=False)
    assert res["ok"] and not res["cached"]


def test_is_current_is_false_for_a_missing_or_empty_file(tmp_path):
    assert not is_current(tmp_path / "nope.cube", 0.0)
    (tmp_path / "empty.cube").write_text("", encoding="utf-8")
    assert not is_current(tmp_path / "empty.cube", 0.0)


def test_the_beta_set_of_a_closed_shell_is_a_refusal_not_a_crash(tmp_path, water):
    res = generate_nbo_cube(water, "h2o", CubeRequest(kind="nbo", index=0, operator=1),
                            dest_dir=tmp_path)
    assert not res["ok"] and "closed-shell" in res["error"]


def test_an_index_out_of_range_is_a_refusal(tmp_path, water):
    res = generate_nbo_cube(water, "h2o", CubeRequest(kind="nbo", index=999), dest_dir=tmp_path)
    assert not res["ok"] and "out of range" in res["error"]


def test_another_kind_is_refused(tmp_path, water):
    res = generate_nbo_cube(water, "h2o", CubeRequest(kind="mo", index=0), dest_dir=tmp_path)
    assert not res["ok"] and "not a natural bond orbital" in res["error"]


def test_the_beta_cube_of_an_open_shell_names_its_spin(tmp_path, cation):
    req = CubeRequest(kind="nbo", index=0, operator=1, grid=40)
    res = generate_nbo_cube(cation, "wcat", req, dest_dir=tmp_path)
    assert res["ok"] and res["label"].endswith("(beta)")
    assert Path(res["path"]).name == "wcat.nbo0b.g40.cube"
    assert "(beta)" in Path(res["path"]).read_text(encoding="utf-8").splitlines()[1]


def test_generate_logs_what_it_did(tmp_path, water):
    lines = []
    generate_nbo_cube(water, "h2o", CubeRequest(kind="nbo", index=3, grid=40),
                      dest_dir=tmp_path, on_log=lines.append)
    assert any("BD (1) O1-H2" in l and "40" in l for l in lines)
    assert any("wrote h2o.nbo3a.g40.cube" in l for l in lines)


def test_cube_title_names_orbital_spin_and_occupancy(water):
    o = water.orbital(0, 3)
    t = cube_title(o, "", water.wavefunction.elements)
    assert t.startswith("Natural bond orbital 3: BD (1) O1-H2, occupancy 1.99")
    assert "(alpha)" in cube_title(o, "alpha", water.wavefunction.elements)


def test_the_drawn_orbital_is_the_ao_vector(tmp_path, water):
    """What lands in the file is the AO-basis vector evaluated on the box --
    checked at the grid's centre point against a direct evaluation."""
    from orcamgr.nbo.grid import cube_grid, orbital_values
    req = CubeRequest(kind="nbo", index=1, grid=40)
    res = generate_nbo_cube(water, "h2o", req, dest_dir=tmp_path)
    lines = Path(res["path"]).read_text(encoding="utf-8").splitlines()
    values = np.array(" ".join(lines[10:]).split(), dtype=float)   # 6 header + 3 atoms + 1 index line
    grid = cube_grid(water.wavefunction, 40)
    i = j = k = 20
    flat = (i * 40 + j) * 40 + k
    pt = np.array([grid.origin[0] + i * grid.step[0], grid.origin[1] + j * grid.step[1],
                   grid.origin[2] + k * grid.step[2]])
    direct = orbital_values(water.wavefunction, water.ao_coefficients(0, 1), pt[None, :])[0]
    assert values[flat] == pytest.approx(direct, abs=1e-5 * max(1.0, abs(direct)))
