"""
Calculation queue with explicit geometry dependencies.

The queue unit is a single *Calculation* (one ORCA run). A calculation's
geometry comes from one of two sources:

* DIRECT    -- coordinates provided up front (typically from an .xyz file)
* REFERENCE -- the optimized geometry of another calculation in the queue,
               named explicitly by the user

Calculations run in queue order. When a calculation references another, the
engine injects the referenced calculation's final geometry at run time.

Failure propagation: if a calculation fails, any calculation that depends on it
(directly or transitively) is marked BLOCKED and skipped. Unrelated calculations
continue. This is dependency-scoped, not whole-queue.

Folder layout: each calculation gets its own folder ``{workspace}/{name}/``.
Names are unique within a queue (enforced at the UI/bridge layer), so folders
never collide.

The engine is GUI-agnostic: it communicates only through callbacks.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Callable, Optional

from .input_generator import StepConfig, build_input, render_raw_input, GEOMETRY_PLACEHOLDER
from .runner import OrcaRunner, OrcaRunError
from .parser import parse_file, ParseResult


class CalcState(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    DONE = "done"
    FAILED = "failed"
    BLOCKED = "blocked"       # a dependency failed, so this never ran
    CANCELLED = "cancelled"


class GeometrySource(str, Enum):
    DIRECT = "direct"
    REFERENCE = "reference"


@dataclass
class Calculation:
    name: str                              # unique; used as folder name
    kind: str                              # opt / freq / tddft / sp
    config: StepConfig
    charge: int = 0
    multiplicity: int = 1

    geometry_source: GeometrySource = GeometrySource.DIRECT
    xyz: str = ""                          # used when source == DIRECT
    ref_name: str = ""                     # used when source == REFERENCE

    # raw mode: user has hand-edited the full .inp text. When True, the engine
    # uses raw_text verbatim (substituting the geometry placeholder if present)
    # instead of generating the .inp from config.
    is_raw: bool = False
    raw_text: str = ""

    state: CalcState = CalcState.PENDING
    message: str = ""
    result: Optional[ParseResult] = None
    output_path: str = ""


# ---- callbacks ----------------------------------------------------------
@dataclass
class QueueCallbacks:
    log: Callable[[str, str], None] = lambda msg, level: None
    calc_update: Callable[[int, "Calculation"], None] = lambda i, c: None


def _xyz_from_geometry(result: ParseResult) -> str:
    return "\n".join(
        f"{a.symbol} {a.x:.10f} {a.y:.10f} {a.z:.10f}" for a in result.geometry
    )


def _as_xyz_file(coords: str) -> str:
    """Wrap a bare coordinate block ('El x y z' lines) as a standard .xyz file:
    an atom-count header, a comment line, then the coordinates. If the text
    already looks like a full .xyz (first line is just an integer), return as-is."""
    lines = [ln for ln in coords.strip().splitlines() if ln.strip()]
    if lines and lines[0].split() and lines[0].split()[0].isdigit() and len(lines[0].split()) == 1:
        return coords.strip() + "\n"   # already has an xyz header
    n = sum(1 for ln in lines if len(ln.split()) >= 4)
    body = "\n".join(lines)
    return f"{n}\ngenerated by ORCAdesk\n{body}\n"


class QueueEngine:
    """Runs a list of Calculations in order, resolving geometry references."""

    def __init__(self, orca_path: str, workspace_root: str,
                 callbacks: Optional[QueueCallbacks] = None,
                 skip_names: Optional[set] = None):
        self.runner = OrcaRunner(orca_path)
        self.workspace_root = Path(workspace_root)
        self.cb = callbacks or QueueCallbacks()
        self._cancelled = False
        self._by_name: dict[str, Calculation] = {}
        # calculations the user chose to skip this run (e.g. to keep existing
        # results on disk instead of overwriting them)
        self._skip_names = set(skip_names or ())

    def cancel(self) -> None:
        self._cancelled = True
        self.runner.cancel()

    # -- geometry resolution --
    def _resolve_geometry(self, calc: Calculation) -> str:
        if calc.geometry_source == GeometrySource.DIRECT:
            # In raw+direct mode the coordinates live inside raw_text already,
            # so an empty xyz here is fine (placeholder won't be used).
            if not calc.xyz.strip() and not calc.is_raw:
                raise OrcaRunError("No coordinates provided (direct source is empty).")
            return calc.xyz
        # REFERENCE
        ref = self._by_name.get(calc.ref_name)
        if ref is None:
            raise OrcaRunError(f"Referenced calculation '{calc.ref_name}' not found in queue.")
        if ref.state == CalcState.DONE and ref.result and ref.result.geometry:
            return _xyz_from_geometry(ref.result)
        if ref.state in (CalcState.FAILED, CalcState.BLOCKED, CalcState.CANCELLED):
            raise OrcaRunError(f"Referenced calculation '{calc.ref_name}' did not succeed.")
        if ref.state == CalcState.DONE and (not ref.result or not ref.result.geometry):
            raise OrcaRunError(
                f"Referenced calculation '{calc.ref_name}' produced no geometry "
                "(was it an optimization?)."
            )
        raise OrcaRunError(f"Referenced calculation '{calc.ref_name}' has no usable geometry yet.")

    # -- single calculation --
    def _run_calc(self, calc: Calculation, index: int) -> None:
        calc.state = CalcState.RUNNING
        self.cb.calc_update(index, calc)

        xyz = self._resolve_geometry(calc)

        calc_dir = self.workspace_root / calc.name
        calc_dir.mkdir(parents=True, exist_ok=True)
        inp_path = calc_dir / f"{calc.name}.inp"
        out_path = calc_dir / f"{calc.name}.out"

        if calc.is_raw:
            # raw mode: use the hand-edited text. If it references geometry,
            # the placeholder must be present so we can inject coordinates.
            if (calc.geometry_source == GeometrySource.REFERENCE
                    and GEOMETRY_PLACEHOLDER not in calc.raw_text):
                raise OrcaRunError(
                    f"Raw input references another calculation but has no "
                    f"{GEOMETRY_PLACEHOLDER} placeholder for the geometry."
                )
            text = render_raw_input(calc.raw_text, xyz)
        else:
            text = build_input(calc.config, xyz, calc.charge, calc.multiplicity)
        inp_path.write_text(text, encoding="utf-8")

        # NEB-TS needs side .xyz files in the run folder that the %neb block
        # points at: the product geometry (required) and an optional TS guess.
        # build_input references fixed names "product.xyz" / "ts_guess.xyz", so
        # write them here from the calc's stored coordinates.
        if not calc.is_raw and calc.config.kind == "neb_ts":
            prod = (calc.config.neb_product_xyz or "").strip()
            if not prod:
                raise OrcaRunError(
                    "NEB-TS needs a product geometry, but none was provided."
                )
            (calc_dir / "product.xyz").write_text(_as_xyz_file(prod), encoding="utf-8")
            guess = (calc.config.neb_ts_guess_xyz or "").strip()
            if guess:
                (calc_dir / "ts_guess.xyz").write_text(_as_xyz_file(guess), encoding="utf-8")

        self.cb.log(f"[{calc.name}] ({calc.kind}) running ORCA...", "info")
        self.runner.run(inp_path, out_path, on_line=lambda ln: self.cb.log(ln, "orca"))

        result = parse_file(str(out_path))
        calc.result = result
        calc.output_path = str(out_path)

        self._validate(calc, result)

        calc.state = CalcState.DONE
        calc.message = "Completed."
        self.cb.log(f"[{calc.name}] done.", "ok")
        self.cb.calc_update(index, calc)

    def _validate(self, calc: Calculation, result: ParseResult) -> None:
        if not result.terminated_normally:
            raise OrcaRunError(
                f"ORCA did not terminate normally. {result.error_message or 'Check the .out file.'}"
            )
        if calc.kind in ("opt", "ts_opt") and not result.opt_converged:
            raise OrcaRunError("Optimization did not converge.")
        if calc.kind == "freq" and result.n_imaginary > 0:
            imag = [f for f in result.frequencies if f < 0]
            detail = ", ".join(f"{v:.2f}" for v in imag[:5])
            raise OrcaRunError(
                f"{result.n_imaginary} imaginary frequency/frequencies "
                f"(cm^-1: {detail}). Not a true minimum."
            )
        if calc.kind == "ts_freq":
            # a genuine transition state has exactly ONE imaginary frequency
            n = result.n_imaginary
            if n == 0:
                raise OrcaRunError(
                    "No imaginary frequency found. Not a transition state "
                    "(a TS should have exactly one)."
                )
            if n > 1:
                imag = [f for f in result.frequencies if f < 0]
                detail = ", ".join(f"{v:.2f}" for v in imag[:5])
                raise OrcaRunError(
                    f"{n} imaginary frequencies (cm^-1: {detail}). A transition "
                    "state should have exactly one; this is a higher-order saddle point."
                )

    # -- dependency-scoped failure propagation --
    def _dependents_of(self, calcs: list[Calculation], failed_name: str) -> set[str]:
        """All calc names that depend on failed_name, directly or transitively."""
        blocked: set[str] = set()
        bad = {failed_name}
        changed = True
        while changed:
            changed = False
            for c in calcs:
                if c.name in blocked:
                    continue
                if (c.geometry_source == GeometrySource.REFERENCE
                        and c.ref_name in bad):
                    blocked.add(c.name)
                    bad.add(c.name)
                    changed = True
        return blocked

    def _failure_reason(self, calc: Calculation, runner_msg: str) -> str:
        """Turn a raw runner error into a user-facing reason. If ORCA wrote an
        .out, read the actual failure cause from it (SCF not converged, etc.);
        otherwise fall back to the runner's message. 'Cancelled' passes through."""
        if "cancel" in runner_msg.lower():
            return runner_msg
        try:
            out_path = self.workspace_root / calc.name / f"{calc.name}.out"
            if out_path.exists():
                from .parser import parse_file
                r = parse_file(str(out_path))
                if r.error_message:
                    return r.error_message
        except Exception:
            pass
        return runner_msg

    # -- the whole queue --
    def run_all(self, calcs: list[Calculation]) -> None:
        self._by_name = {c.name: c for c in calcs}
        blocked_names: set[str] = set()

        for i, calc in enumerate(calcs):
            if self._cancelled:
                calc.state = CalcState.CANCELLED
                calc.message = "Cancelled."
                self.cb.calc_update(i, calc)
                continue

            if calc.name in blocked_names:
                calc.state = CalcState.BLOCKED
                calc.message = "Skipped: a dependency failed."
                self.cb.log(f"[{calc.name}] blocked (a dependency failed).", "warn")
                self.cb.calc_update(i, calc)
                continue

            # Already finished successfully on a previous run: don't recompute
            # (that would waste time and overwrite good results). FAILED and
            # CANCELLED calculations DO re-run, so the user can retry them.
            if calc.state == CalcState.DONE:
                self.cb.log(f"[{calc.name}] already done \u2014 skipping.", "info")
                self.cb.calc_update(i, calc)
                continue

            # User chose to keep the existing result on disk for this one.
            # Load that .out (so references and the Results tab still work)
            # instead of recomputing and overwriting it.
            if calc.name in self._skip_names:
                out_path = self.workspace_root / calc.name / f"{calc.name}.out"
                try:
                    if out_path.exists():
                        calc.result = parse_file(str(out_path))
                        calc.output_path = str(out_path)
                        calc.state = CalcState.DONE
                        calc.message = "Kept existing result (not recomputed)."
                        self._by_name[calc.name] = calc
                        self.cb.log(f"[{calc.name}] kept existing result on disk \u2014 not recomputed.", "info")
                    else:
                        # nothing on disk after all; fall through and run it
                        self.cb.log(f"[{calc.name}] no existing result found; running.", "warn")
                        self._skip_names.discard(calc.name)
                except Exception as e:
                    self.cb.log(f"[{calc.name}] could not read existing result ({e}); running.", "warn")
                    self._skip_names.discard(calc.name)
                if calc.name in self._skip_names:
                    self.cb.calc_update(i, calc)
                    continue

            try:
                self._run_calc(calc, i)
            except OrcaRunError as e:
                calc.state = CalcState.FAILED
                calc.message = self._failure_reason(calc, str(e))
                self.cb.log(f"[{calc.name}] FAILED: {calc.message}", "err")
                self.cb.calc_update(i, calc)
                blocked_names |= self._dependents_of(calcs, calc.name)
            except Exception as e:  # defensive
                calc.state = CalcState.FAILED
                calc.message = f"Unexpected error: {e}"
                self.cb.log(f"[{calc.name}] FAILED: {e}", "err")
                self.cb.calc_update(i, calc)
                blocked_names |= self._dependents_of(calcs, calc.name)
