"""
Calculation queue with explicit geometry dependencies.

The queue unit is a single *Calculation* (one ORCA run). A calculation's
geometry comes from one of two sources:

* DIRECT    -- coordinates provided up front (typically from an .xyz file)
* REFERENCE -- the optimized geometry of another calculation in the queue,
               named explicitly by the user

Calculations run in queue order. When a calculation references another, the
engine injects the referenced calculation's final geometry at run time.

Failure propagation: if a calculation fails, any calculation that depends on it
(directly or transitively) is marked BLOCKED and skipped. Unrelated calculations
continue. This is dependency-scoped, not whole-queue.

Folder layout: each calculation gets its own folder ``{workspace}/{name}/``.
Names are unique within a queue (enforced at the UI/bridge layer), so folders
never collide.

The engine is GUI-agnostic: it communicates only through callbacks.
"""

from __future__ import annotations

import threading
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Callable, Optional

from .input_generator import (
    StepConfig, build_input, render_raw_input, GEOMETRY_PLACEHOLDER, check_neb_atom_order,
)
from .runner import OrcaRunner, OrcaRunError, OrcaCancelled, OrcaDetached
from .parser import parse_file, ParseResult
from .procutil import process_matches


class CalcState(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    DONE = "done"
    FAILED = "failed"
    BLOCKED = "blocked"       # a dependency failed, so this never ran
    CANCELLED = "cancelled"


class GeometrySource(str, Enum):
    DIRECT = "direct"
    REFERENCE = "reference"


@dataclass
class Calculation:
    name: str                              # unique; used as folder name
    kind: str                              # opt / freq / tddft / sp
    config: StepConfig
    charge: int = 0
    multiplicity: int = 1

    geometry_source: GeometrySource = GeometrySource.DIRECT
    xyz: str = ""                          # used when source == DIRECT
    ref_name: str = ""                     # used when source == REFERENCE

    # raw mode: user has hand-edited the full .inp text. When True, the engine
    # uses raw_text verbatim (substituting the geometry placeholder if present)
    # instead of generating the .inp from config.
    is_raw: bool = False
    raw_text: str = ""

    state: CalcState = CalcState.PENDING
    message: str = ""
    result: Optional[ParseResult] = None
    output_path: str = ""

    # set while RUNNING: the OS identity of the detached ORCA process, persisted
    # so a run left going when ORCAdesk closes can be reattached on next launch.
    pid: Optional[int] = None
    create_time: Optional[float] = None


# ---- callbacks ----------------------------------------------------------
@dataclass
class QueueCallbacks:
    log: Callable[[str, str], None] = lambda msg, level: None
    calc_update: Callable[[int, "Calculation"], None] = lambda i, c: None


def _xyz_from_geometry(result: ParseResult) -> str:
    return "\n".join(
        f"{a.symbol} {a.x:.10f} {a.y:.10f} {a.z:.10f}" for a in result.geometry
    )


def _as_xyz_file(coords: str) -> str:
    """Wrap a bare coordinate block ('El x y z' lines) as a standard .xyz file:
    an atom-count header, a comment line, then the coordinates. If the text
    already looks like a full .xyz (first line is just an integer), return as-is."""
    lines = [ln for ln in coords.strip().splitlines() if ln.strip()]
    if lines and lines[0].split() and lines[0].split()[0].isdigit() and len(lines[0].split()) == 1:
        return coords.strip() + "\n"   # already has an xyz header
    n = sum(1 for ln in lines if len(ln.split()) >= 4)
    body = "\n".join(lines)
    return f"{n}\ngenerated by ORCAdesk\n{body}\n"


def validate_result(calc: Calculation, result: ParseResult) -> None:
    """Per-kind result validation, raising OrcaRunError on a bad result. Module-
    level so both the live engine and session reconciliation (after a restart)
    apply identical rules: opt/ts_opt must converge; freq must have zero
    imaginary modes; ts_freq exactly one; neb_ts (when freqs were computed)
    exactly one."""
    if not result.terminated_normally:
        raise OrcaRunError(
            f"ORCA did not terminate normally. {result.error_message or 'Check the .out file.'}"
        )
    if calc.kind in ("opt", "ts_opt", "opt_freq", "ts_opt_freq") and not result.opt_converged:
        raise OrcaRunError("Optimization did not converge.")
    if calc.kind in ("freq", "opt_freq") and result.n_imaginary > 0:
        imag = [f for f in result.frequencies if f < 0]
        detail = ", ".join(f"{v:.2f}" for v in imag[:5])
        raise OrcaRunError(
            f"{result.n_imaginary} imaginary frequency/frequencies "
            f"(cm^-1: {detail}). Not a true minimum."
        )
    if calc.kind in ("ts_freq", "ts_opt_freq"):
        # a genuine transition state has exactly ONE imaginary frequency
        n = result.n_imaginary
        if n == 0:
            raise OrcaRunError(
                "No imaginary frequency found. Not a transition state "
                "(a TS should have exactly one)."
            )
        if n > 1:
            imag = [f for f in result.frequencies if f < 0]
            detail = ", ".join(f"{v:.2f}" for v in imag[:5])
            raise OrcaRunError(
                f"{n} imaginary frequencies (cm^-1: {detail}). A transition "
                "state should have exactly one; this is a higher-order saddle point."
            )
    if calc.kind == "neb_ts" and result.frequencies:
        # preset_neb_ts appends FREQ to verify the located TS. If frequencies
        # were computed, require exactly one imaginary mode (a true first-order
        # saddle); skip the check when the user removed FREQ (no frequencies).
        n = result.n_imaginary
        if n != 1:
            imag = [f for f in result.frequencies if f < 0]
            detail = ", ".join(f"{v:.2f}" for v in imag[:5]) if imag else "none"
            raise OrcaRunError(
                f"NEB-TS located a structure with {n} imaginary frequency/frequencies "
                f"(cm^-1: {detail}); a transition state must have exactly one."
            )


class QueueEngine:
    """Runs a list of Calculations in order, resolving geometry references."""

    def __init__(self, orca_path: str, workspace_root: str,
                 callbacks: Optional[QueueCallbacks] = None,
                 skip_names: Optional[set] = None):
        self.runner = OrcaRunner(orca_path)
        self.workspace_root = Path(workspace_root)
        self.cb = callbacks or QueueCallbacks()
        # hard cancel: kill the current job and skip the rest (CANCELLED).
        self._cancel_event = threading.Event()
        # graceful drain: let the current job finish, then stop; the rest stay
        # PENDING so they remain runnable on the next Run.
        self._stop_after_current = threading.Event()
        # shutdown detach: stop monitoring but LEAVE the running ORCA alive so it
        # survives the app closing and can be reattached next launch.
        self._detach_event = threading.Event()
        self._by_name: dict[str, Calculation] = {}
        # calculations the user chose to skip this run (e.g. to keep existing
        # results on disk instead of overwriting them)
        self._skip_names = set(skip_names or ())

    def cancel(self) -> None:
        self._cancel_event.set()
        self.runner.cancel()

    def request_stop_after_current(self) -> None:
        """Stop processing once the in-flight job finishes; leave the remaining
        calculations PENDING. Does NOT kill the running job."""
        self._stop_after_current.set()

    def detach(self) -> None:
        """Stop monitoring the queue WITHOUT killing the running ORCA — used on
        app shutdown so the in-flight job survives and can be reattached. The
        running calc is left in the RUNNING state (its pid is already persisted)."""
        self._detach_event.set()
        self.runner.detach()

    # -- geometry resolution --
    def _resolve_geometry(self, calc: Calculation) -> str:
        if calc.geometry_source == GeometrySource.DIRECT:
            # In raw+direct mode the coordinates live inside raw_text already,
            # so an empty xyz here is fine (placeholder won't be used).
            if not calc.xyz.strip() and not calc.is_raw:
                raise OrcaRunError("No coordinates provided (direct source is empty).")
            return calc.xyz
        # REFERENCE
        if calc.ref_name == calc.name:
            raise OrcaRunError("A calculation can't reference its own geometry.")
        ref = self._by_name.get(calc.ref_name)
        if ref is None:
            raise OrcaRunError(f"Referenced calculation '{calc.ref_name}' not found in queue.")
        # Parse-on-miss: a DONE ref restored from a previous session has no
        # in-memory ParseResult (we don't eagerly re-parse on load), so read its
        # .out now — at run time, gated behind a multi-minute ORCA job anyway.
        if ref.state == CalcState.DONE and not ref.result and ref.output_path:
            try:
                ref.result = parse_file(ref.output_path)
            except Exception:
                pass  # leave result None; the checks below give a clear error
        if ref.state == CalcState.DONE and ref.result and ref.result.geometry:
            return _xyz_from_geometry(ref.result)
        if ref.state in (CalcState.FAILED, CalcState.BLOCKED, CalcState.CANCELLED):
            raise OrcaRunError(f"Referenced calculation '{calc.ref_name}' did not succeed.")
        if ref.state == CalcState.DONE and (not ref.result or not ref.result.geometry):
            raise OrcaRunError(
                f"Referenced calculation '{calc.ref_name}' produced no geometry "
                "(was it an optimization?)."
            )
        raise OrcaRunError(f"Referenced calculation '{calc.ref_name}' has no usable geometry yet.")

    # -- single calculation --
    def _run_calc(self, calc: Calculation, index: int) -> None:
        out_path = self.workspace_root / calc.name / f"{calc.name}.out"

        # Reattach path: this calc was left RUNNING by a previous session and its
        # ORCA process is genuinely still alive — don't relaunch, just resume
        # monitoring the live process and tailing its .out.
        if (calc.state == CalcState.RUNNING and calc.pid
                and process_matches(calc.pid, calc.create_time)):
            self.runner.adopt(calc.pid, calc.create_time)
            self.cb.log(f"[{calc.name}] reattaching to ORCA still running "
                        f"(pid {calc.pid})...", "info")
            self.cb.calc_update(index, calc)
            # Tail from the CURRENT end of file: don't re-stream the output
            # written before the app closed (that would flood the live log and,
            # past the log-buffer cap, truncate the graph). The UI rebuilds the
            # full SCF/opt-graph history separately from the .out on disk.
            start_pos = self.runner.end_position(out_path)
            self._monitor_and_finish(calc, index, out_path, start_pos=start_pos)
            return

        # Fresh launch.
        calc.state = CalcState.RUNNING
        self.cb.calc_update(index, calc)

        xyz = self._resolve_geometry(calc)

        calc_dir = self.workspace_root / calc.name
        calc_dir.mkdir(parents=True, exist_ok=True)
        inp_path = calc_dir / f"{calc.name}.inp"

        if calc.is_raw:
            # raw mode: use the hand-edited text. If it references geometry,
            # the placeholder must be present so we can inject coordinates.
            if (calc.geometry_source == GeometrySource.REFERENCE
                    and GEOMETRY_PLACEHOLDER not in calc.raw_text):
                raise OrcaRunError(
                    f"Raw input references another calculation but has no "
                    f"{GEOMETRY_PLACEHOLDER} placeholder for the geometry."
                )
            text = render_raw_input(calc.raw_text, xyz)
        else:
            text = build_input(calc.config, xyz, calc.charge, calc.multiplicity)
        inp_path.write_text(text, encoding="utf-8")

        # NEB-TS needs side .xyz files in the run folder that the %neb block
        # points at: the product geometry (required) and an optional TS guess.
        # build_input references fixed names "product.xyz" / "ts_guess.xyz", so
        # write them here. This must also happen in RAW mode — a raw NEB-TS keeps
        # the NEB_End_XYZFile "product.xyz" reference, so the file must exist.
        if calc.kind == "neb_ts":
            prod = (calc.config.neb_product_xyz or "").strip()
            if not calc.is_raw:
                if not prod:
                    raise OrcaRunError("NEB-TS needs a product geometry, but none was provided.")
                # reactant (xyz) and product must have identical atoms in identical
                # order — catch the #1 NEB-TS user error before launching ORCA.
                chk = check_neb_atom_order(xyz, prod)
                if not chk.get("ok"):
                    raise OrcaRunError(chk.get("error") or "NEB-TS reactant/product atom mismatch.")
            if prod:
                (calc_dir / "product.xyz").write_text(_as_xyz_file(prod), encoding="utf-8")
                guess = (calc.config.neb_ts_guess_xyz or "").strip()
                if guess:
                    (calc_dir / "ts_guess.xyz").write_text(_as_xyz_file(guess), encoding="utf-8")

        self.cb.log(f"[{calc.name}] ({calc.kind}) running ORCA...", "info")
        pid, create_time = self.runner.launch(inp_path, out_path)
        calc.pid = pid
        calc.create_time = create_time
        # persist the pid immediately so a reattach is possible even if ORCAdesk
        # is closed seconds after the job starts.
        self.cb.calc_update(index, calc)

        self._monitor_and_finish(calc, index, out_path)

    def _monitor_and_finish(self, calc: Calculation, index: int, out_path,
                            start_pos: int = 0) -> None:
        """Tail ORCA's output until it exits (or is cancelled/detached), then
        parse + validate + mark DONE. Shared by the fresh-launch and reattach
        paths (reattach passes start_pos = current EOF). OrcaCancelled /
        OrcaDetached propagate to run_all."""
        self.runner.monitor(out_path, on_line=lambda ln: self.cb.log(ln, "orca"),
                            start_pos=start_pos)

        result = parse_file(str(out_path))
        calc.result = result
        calc.output_path = str(out_path)

        validate_result(calc, result)

        calc.state = CalcState.DONE
        calc.pid = None
        calc.create_time = None
        calc.message = "Completed."
        self.cb.log(f"[{calc.name}] done.", "ok")
        self.cb.calc_update(index, calc)

    # -- dependency-scoped failure propagation --
    def _dependents_of(self, calcs: list[Calculation], failed_name: str) -> set[str]:
        """All calc names that depend on failed_name, directly or transitively."""
        blocked: set[str] = set()
        bad = {failed_name}
        changed = True
        while changed:
            changed = False
            for c in calcs:
                if c.name in blocked:
                    continue
                if (c.geometry_source == GeometrySource.REFERENCE
                        and c.ref_name in bad):
                    blocked.add(c.name)
                    bad.add(c.name)
                    changed = True
        return blocked

    def _failure_reason(self, calc: Calculation, runner_msg: str) -> str:
        """Turn a raw runner error into a user-facing reason. If ORCA wrote an
        .out, read the actual failure cause from it (SCF not converged, etc.);
        otherwise fall back to the runner's message. 'Cancelled' passes through."""
        if "cancel" in runner_msg.lower():
            return runner_msg
        try:
            out_path = self.workspace_root / calc.name / f"{calc.name}.out"
            if out_path.exists():
                r = parse_file(str(out_path))
                if r.error_message:
                    return r.error_message
        except Exception as e:
            # Diagnosing the failure must not itself fail silently — fall back to
            # the raw runner message, but leave a breadcrumb so a broken parse
            # path is discoverable instead of swallowed.
            self.cb.log(f"[{calc.name}] could not parse .out for a detailed reason ({e}).", "warn")
        return runner_msg

    # -- the whole queue --
    def run_all(self, calcs: list[Calculation]) -> None:
        self._by_name = {c.name: c for c in calcs}
        blocked_names: set[str] = set()

        for i, calc in enumerate(calcs):
            if self._detach_event.is_set():
                # App is shutting down: stop processing and leave every calc as
                # it is (a RUNNING one keeps going in the background for reattach).
                break

            if self._cancel_event.is_set():
                calc.state = CalcState.CANCELLED
                calc.message = "Cancelled."
                calc.pid = None
                calc.create_time = None
                self.cb.calc_update(i, calc)
                continue

            # Graceful drain: the user asked to stop AFTER the current job. By
            # now that job has finished; leave the remaining calcs PENDING (so
            # they stay runnable) and stop processing the queue.
            if self._stop_after_current.is_set():
                remaining = sum(1 for c in calcs[i:] if c.state == CalcState.PENDING)
                self.cb.log(
                    f"Stopped after current job; {remaining} calculation(s) left pending.",
                    "info",
                )
                break

            if calc.name in blocked_names:
                calc.state = CalcState.BLOCKED
                calc.message = "Skipped: a dependency failed."
                self.cb.log(f"[{calc.name}] blocked (a dependency failed).", "warn")
                self.cb.calc_update(i, calc)
                continue

            # Already finished successfully on a previous run: don't recompute
            # (that would waste time and overwrite good results). FAILED and
            # CANCELLED calculations DO re-run, so the user can retry them.
            if calc.state == CalcState.DONE:
                self.cb.log(f"[{calc.name}] already done \u2014 skipping.", "info")
                self.cb.calc_update(i, calc)
                continue

            # User chose to keep the existing result on disk for this one.
            # Load that .out (so references and the Results tab still work)
            # instead of recomputing and overwriting it.
            if calc.name in self._skip_names:
                out_path = self.workspace_root / calc.name / f"{calc.name}.out"
                try:
                    if out_path.exists():
                        calc.result = parse_file(str(out_path))
                        calc.output_path = str(out_path)
                        calc.state = CalcState.DONE
                        calc.message = "Kept existing result (not recomputed)."
                        self._by_name[calc.name] = calc
                        self.cb.log(f"[{calc.name}] kept existing result on disk \u2014 not recomputed.", "info")
                    else:
                        # nothing on disk after all; fall through and run it
                        self.cb.log(f"[{calc.name}] no existing result found; running.", "warn")
                        self._skip_names.discard(calc.name)
                except Exception as e:
                    self.cb.log(f"[{calc.name}] could not read existing result ({e}); running.", "warn")
                    self._skip_names.discard(calc.name)
                if calc.name in self._skip_names:
                    self.cb.calc_update(i, calc)
                    continue

            try:
                self._run_calc(calc, i)
            except OrcaDetached:
                # app shutdown mid-calc: leave THIS calc RUNNING (its ORCA keeps
                # going headless; pid is persisted) and stop processing so it can
                # be reattached on the next launch. Do not touch its state.
                self.cb.log(f"[{calc.name}] left running in the background.", "info")
                break
            except OrcaCancelled:
                # user stopped the run mid-calc: mark THIS calc CANCELLED (not
                # FAILED) and do NOT block its dependents — the remaining calcs
                # are marked CANCELLED by the top-of-loop guard on the next pass.
                calc.state = CalcState.CANCELLED
                calc.message = "Cancelled by user."
                calc.pid = None
                calc.create_time = None
                self.cb.log(f"[{calc.name}] cancelled.", "info")
                self.cb.calc_update(i, calc)
            except OrcaRunError as e:
                calc.state = CalcState.FAILED
                calc.message = self._failure_reason(calc, str(e))
                calc.pid = None
                calc.create_time = None
                self.cb.log(f"[{calc.name}] FAILED: {calc.message}", "err")
                self.cb.calc_update(i, calc)
                blocked_names |= self._dependents_of(calcs, calc.name)
            except Exception as e:  # defensive
                calc.state = CalcState.FAILED
                calc.message = f"Unexpected error: {e}"
                calc.pid = None
                calc.create_time = None
                self.cb.log(f"[{calc.name}] FAILED: {e}", "err")
                self.cb.calc_update(i, calc)
                blocked_names |= self._dependents_of(calcs, calc.name)
