"""
Small .xyz text helpers shared by the ORCA, MLIP and CREST pipelines.

Backend-agnostic on purpose: crest/ and mlip/ stay independent of core/queue
but may depend on core/ leaf modules like this one (they already import
core.runner for the run-error types).
"""

from __future__ import annotations


def as_xyz_file(coords: str) -> str:
    """Wrap a bare coordinate block ('El x y z' lines) as a standard .xyz file:
    an atom-count header, a comment line, then the coordinates. If the text
    already looks like a full .xyz (first line is just an integer), return as-is."""
    lines = [ln for ln in coords.strip().splitlines() if ln.strip()]
    if lines and lines[0].split() and lines[0].split()[0].isdigit() and len(lines[0].split()) == 1:
        return coords.strip() + "\n"   # already has an xyz header
    n = sum(1 for ln in lines if len(ln.split()) >= 4)
    body = "\n".join(lines)
    return f"{n}\ngenerated by ORCAdesk\n{body}\n"
